### ISSUE TITLE
GUI Fixes

### ISSUE THREAD

**Issue by MoseslGit** [anirudhbhalekar/GF2P2#15]
1. Canvas deletion on open broken file, then open working file: Canvas being deleted makes it so we can't open the working file afterwards (+ 3D visualization breaks when opening broken file in 2D then switching to 3D)
2. Command line run doesn't work for 3D Mode
3. Reframe monitor plots in 3D so we can see all of them initially

**Comment by MoseslGit** [comment]
4. Increase maximum cycle number to be run at one time in GUI

**Comment by anirudhbhalekar** [comment]
I am going to enumerate fixes here 

> 1 - going to force software into 2D mode when we load a new file, will untoggle 3D mode button, set is3D to false, then load new canvas

**Comment by MoseslGit** [comment]
5. Need to throw error for command line m X - currently says "adding monitor on signal X" but should say Adding monitor failed etc.

**Comment by MoseslGit** [comment]
6. running simulation for negative cycles in command line should throw an error (r -10), currently says "running simulation"

**Comment by anirudhbhalekar** [comment]
> 1 was fixed by only changing names, devices... etc IFF parser.parse network on the new file was true
> 2 Command line uses a use-case system, have not implemented is3D functionality yet will do that

**Comment by MoseslGit** [comment]
7. Reset Plot in 3D mode doesn't reset the plot in 2D

**Comment by anirudhbhalekar** [comment]
> 2 has been fixed 
> can fix 3 by changing init camera so its facing forward instead of facing below

**Comment by anirudhbhalekar** [comment]
> 4 is trivial, just increase in gui
> 6 is also trivial - have added a check for N in the text box command

**Comment by anirudhbhalekar** [comment]
> 7 have now cleared axes when reset plot is called - so data is always removed

**Comment by anirudhbhalekar** [comment]
> 5 is also done - referred to outputs from make_monitor from monitors class
