### ISSUE TITLE
Interim Feedback 1

### ISSUE THREAD

**Issue by MoseslGit** [anirudhbhalekar/GF2P2#2]
According to the feedback given for Interim Report 1, we need to implement the following:

- Skip comments in Scanner instead of passing to Parser as "COMMENT" symbol
- Remove float option from value definition in EBNF rule
- Integrate errors into one unified code
- Include missing semantic errors

**Comment by anirudhbhalekar** [comment]
Right - 

- Skip comment method has been implemented instead so we just advance until the comment termination symbol is seen
- Float option removed from parser
- Integration is already inherent in parser (I believe?)
- Will list more semantic errors in group meeting

**Comment by anirudhbhalekar** [comment]
* Also added an extra feature where '#' defines a single line comment (entire line is commented out, so comment stops once the scanner passes over the newline symbol)

**Comment by MoseslGit** [comment]
This section was not included in the first submitted report by mistake, but for reference comments were defined as:

Although we have not added comments in the EBNF definition above, our scanner will be equipped to deal with comments. Comments will be introduced and ended with the percent sign, as in the following example:

\begin{verbatim}
    % This is a comment %
\end{verbatim}

Because our language is not sensitive to line breaks, comments can extend over multiple lines as long as they start and end with the percent sign.
