### ISSUE TITLE
Parser unit tests are failing

### ISSUE THREAD

**Issue by anirudhbhalekar** [anirudhbhalekar/GF2P2#4]
Scanning tests are working now - made some sample definition files for parser but it isn't catching errors and throwing some errors which are unexpected (for files that should be fine). Also throwing repeated errors (at the same character count which should not happen)

**Comment by MoseslGit** [comment]
I think main current problem is that I didn't add error skipping - this has been mostly fixed, but also need an EOF symbol to be passed to accurately terminate.
