### ISSUE TITLE
Parser error for output connections

### ISSUE THREAD

**Issue by anirudhbhalekar** [anirudhbhalekar/GF2P2#5]
```
def output_con(self):
          """Implements rule output_con = name, [".", output_notation];"""
          self.name()
          if self.symbol.type == self.scanner.DOT:
              self.symbol = self.scanner.get_symbol()
              self.output_notation()
          else:
              #self.error(self.EXPECTED_PUNCTUATION)
              pass
```

I've commented out the else condition. Technically we refer to the sole output pin of a GATE by just referring to its name. We probably want to apply the semantic constraint (if no DOT is observed after check if name corresponds to a GATE, if it refers to a DEVICE then we need a dot and an output_con() reference.

**Comment by MoseslGit** [comment]
For now, this is handled as a pass if we hit a semicolon, and will include semantic error handling after unit tests are complete for syntax
    def output_con(self):
        """Implements rule output_con = name, [".", output_notation];"""
        self.name()
        if self.symbol.type == self.scanner.DOT:
            self.symbol = self.scanner.get_symbol()
            self.output_notation()
        elif self.symbol.type == self.scanner.SEMICOLON:
            pass
        else:
            self.error(self.EXPECTED_PUNCTUATION)
